import './globals.css';
import type { Metadata } from 'next';
import Script from 'next/script';
import localFont from 'next/font/local';
import Header from '../components/header';
import Footer from '../components/footer';
import GlobalModal from '@/components/globalModal';

const pretendard = localFont({
  src: [
    { path: '../public/fonts/Pretendard-Thin.woff2', weight: '100' },
    { path: '../public/fonts/Pretendard-ExtraLight.woff2', weight: '200' },
    { path: '../public/fonts/Pretendard-Light.woff2', weight: '300' },
    { path: '../public/fonts/Pretendard-Regular.woff2', weight: '400' },
    { path: '../public/fonts/Pretendard-Medium.woff2', weight: '500' },
    { path: '../public/fonts/Pretendard-SemiBold.woff2', weight: '600' },
    { path: '../public/fonts/Pretendard-Bold.woff2', weight: '700' },
    { path: '../public/fonts/Pretendard-ExtraBold.woff2', weight: '800' },
    { path: '../public/fonts/Pretendard-Black.woff2', weight: '900' },
  ],
  variable: '--font-pretendard',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body className="flex min-h-screen flex-col">
        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
        <GlobalModal />
        <Script
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_MAP_KEY}&libraries=services,clusterer&autoload=false`}
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
